export const INSTRUMENTS = [
  'Klassischer Gesang',
  'Moderner Gesang',
  'Vocalcoaching',
  'Gesang',
  'Tenor',
  'Bühnencoaching',
  'Klavier',
  'Keyboard',
  'Gitarre',
  'Flamenco Gitarre',
  'Klassische Gitarre',
  'E-Gitarre',
  'E-Bass',
  'Cello',
  'Saxophon',
  'Klarinette',
  'Blockflöte',
  'Steptanz',
  'Kompositionslehre',
  'Musikproduktion',
  'Musikalische Grundschulung',
  'andere'
] as const;